### ISSUE TITLE
Running this project gives a 500 error -Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by vinitha-k** [samppis/React.MVC6.Sample#1]

**Comment by mashbrno** [comment]
Same error here. Callstack:

```
Error initialising System.Func`1[JavaScriptEngineSwitcher.Core.IJsEngine]: JavaScriptEngineSwitcher.Core.JsEngineLoadException: During loading of V8 JavaScript engine error has occurred.  

Cannot load V8 interface assembly. Load failure information for v8-ia32.dll:
C:\Users\Honza\.dnx\packages\JavaScriptEngineSwitcher.V8\1.4.1\lib\net40\v8-ia32.dll: The specified module could not be found
C:\Users\Honza\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\v8-ia32.dll: The specified module could not be found ---> System.TypeLoadException: Cannot load V8 interface assembly. Load failure information for v8-ia32.dll:
C:\Users\Honza\.dnx\packages\JavaScriptEngineSwitcher.V8\1.4.1\lib\net40\v8-ia32.dll: The specified module could not be found
C:\Users\Honza\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\v8-ia32.dll: The specified module could not be found
   at Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary()
   at Microsoft.ClearScript.V8.V8Proxy.LoadAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
   at Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, Boolean enableDebugging, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Configuration config)
   --- End of inner exception stack trace ---
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Configuration config)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor()
   at React.AssemblyRegistration.<>c.<RegisterSupportedEngines>b__3_0()
   at React.JavaScriptEngineFactory.GetFactory(IEnumerable`1 availableFactories, Boolean allowMsie)
```
